kind: pipeline
name: 4.10.0+stock+serial

platform:
  os: linux
  arch: amd64

steps:
- name: 4.10.0+stock
  image: ocurrent/opam:ubuntu-18.04-ocaml-4.10
  commands:
  - sudo apt-get update && sudo apt-get -y install wget pkg-config libgmp-dev m4 libdw-dev jq python3-pip
  - pip3 install intervaltree
  - sudo chown -R opam .
  - eval $(opam env)
  - opam update
  - opam install dune.2.6.0
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make run_config_ci.json
  - RUN_CONFIG_JSON=run_config_ci.json make ocaml-versions/4.10.0+stock.bench

---
kind: pipeline
name: 4.10.0+multicore+serial

platform:
  os: linux
  arch: amd64

steps:
- name: 4.10.0+multicore+serial
  image: ocurrent/opam:ubuntu-18.04-ocaml-4.10
  commands:
  - sudo apt-get update && sudo apt-get -y install wget pkg-config libgmp-dev m4 libdw-dev jq python3-pip
  - pip3 install intervaltree
  - sudo chown -R opam .
  - eval $(opam env)
  - opam update
  - opam install dune.2.6.0
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make run_config_ci.json
  - RUN_CONFIG_JSON=run_config_ci.json make ocaml-versions/4.10.0+multicore.bench

---
kind: pipeline
name: 4.10.0+multicore+parallel

platform:
  os: linux
  arch: amd64

steps:
- name: 4.10.0+multicore+parallel
  image: ocurrent/opam:ubuntu-18.04-ocaml-4.10
  commands:
  - sudo apt-get update && sudo apt-get -y install wget pkg-config libgmp-dev m4 libdw-dev jq python3-pip
  - pip3 install intervaltree
  - sudo chown -R opam .
  - eval $(opam env)
  - opam update
  - opam install dune.2.6.0
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make multicore_parallel_run_config_macro_2domains_ci.json
  - BUILD_BENCH_TARGET=multibench_parallel RUN_CONFIG_JSON=multicore_parallel_run_config_macro_2domains_ci.json make ocaml-versions/4.10.0+multicore.bench
