[workspace]

members = [
    "ocaml-jit-staticlib",         # main static library
    "ocaml-bytecode",              # type definitions for OCaml bytecode
    "ocaml-jit-tools"              # standalone tools (dissasembler, hex dump) for bytecode files and testing the JIT
]
